# libraries

In [ ]:
import pandas as pd  
import numpy as np 
from sklearn.model_selection import train_test_split

In [21]:
import openpyxl

# load Dataset

- #### data is store in Xlsx we will use method from pandas to do it

In [2]:
def load_data (file_path) : 
    df = pd.read_excel(file_path) 
    return df

In [3]:
# !pwd

In [4]:
# !pip install openpyxl

In [5]:
file_path = '../../data/raw_data.xlsx' 

df = load_data(file_path) 
df

,Brand,Model,Year,EngineSize,Fuel,Transmission,Mileage,Doors,OwnerCount,Price
0,Kia,Rio,2020,4.2,Diesel,Manual,289944,3,5,8501
1,Chevrolet,Malibu,2012,2.0,Hybrid,Automatic,5356,2,3,12092
2,Mercedes,GLA,2020,4.2,Diesel,Automatic,231440,4,2,11171
3,Audi,Q5,2023,2.0,Electric,Manual,160971,2,1,11780
4,Volkswagen,Golf,2003,2.6,Hybrid,Semi-Automatic,286618,3,3,2867
...,...,...,...,...,...,...,...,...,...,...
9995,Kia,Optima,2004,3.7,Diesel,Semi-Automatic,5794,2,4,8884
9996,Chevrolet,Impala,2002,1.4,Electric,Automatic,168000,2,1,6240
9997,BMW,3 Series,2010,3.0,Petrol,Automatic,86664,5,1,9866
9998,Ford,Explorer,2002,1.4,Hybrid,Automatic,225772,4,1,4084
9999,Volkswagen,Tiguan,2001,2.1,Diesel,Manual,157882,3,3,3342

- ### first we split data to prevent data leakage and for later analysis

In [6]:
## make sure target is price feature 
X = df.drop('Price' , axis= 1) 
y = df['Price']

In [7]:
X_train , X_test , y_train , y_test = train_test_split (X , y , 
                                                        test_size= 0.2 , 
                                                        random_state=42) 
# make copy from x_train to df to work on it  

df = X_train.copy() 
# we make price column for analysis and cleaning 
df['Price'] = y_train

## remove extra colunms

- #### in this project, we don't have any unnecessary columns ===>skip this step

## columns Typecasting

- #### check data type of columns

In [8]:
df.dtypes

Brand               str
Model               str
Year              int64
EngineSize      float64
Fuel                str
Transmission        str
Mileage           int64
Doors             int64
OwnerCount        int64
Price             int64
dtype: object

- #### there is no isuss here

# handel missing values

- ### iterate through each column and calculate `number` of missing values and percent of each column

In [9]:
""" 
    Mahmoud implementation 

"""
# for col in df.columns : 
#     print(f'number of missing values is {df[col].isna().sum()} and percent of missing values in this column is {df[col].isna().sum() / len(df)}') 


"""
    implementation of mehrdad
"""
for col in df.columns : 
    number_of_null = df.loc[: , col].isna().sum() 
    perc_null = (number_of_null / df.shape[0] ) * 100 

    print(f'in column {col} - {number_of_null} - {perc_null}%')

in column Brand - 0 - 0.0%
in column Model - 0 - 0.0%
in column Year - 0 - 0.0%
in column EngineSize - 0 - 0.0%
in column Fuel - 0 - 0.0%
in column Transmission - 0 - 0.0%
in column Mileage - 0 - 0.0%
in column Doors - 0 - 0.0%
in column OwnerCount - 0 - 0.0%
in column Price - 0 - 0.0%

## handel duplicates

In [10]:
duplicate_rows = df.duplicated() 
if duplicate_rows.any() : 
    print('There is Duplicated') 
else : 
    print('No Duplication')

No Duplication

# Numerical sanity check 

first of all , i declare a;; numerical variables 
- Year , ....

In [11]:
numrical_cols = df.select_dtypes('number').columns.to_list() 
numrical_cols

['Year', 'EngineSize', 'Mileage', 'Doors', 'OwnerCount', 'Price']

In [12]:
df[numrical_cols].describe()

,Year,EngineSize,Mileage,Doors,OwnerCount,Price
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,2011.520375,2.996887,149477.003250,3.503625,2.991875,8828.745250
std,6.897792,1.153237,86613.284937,1.111482,1.420849,3132.164285
min,2000.000000,1.000000,25.000000,2.000000,1.000000,2000.000000
25%,2006.000000,2.000000,74192.250000,3.000000,2.000000,6604.750000
50%,2012.000000,3.000000,150069.500000,4.000000,3.000000,8829.000000
75%,2017.000000,4.000000,224292.750000,4.000000,4.000000,11071.000000
max,2023.000000,5.000000,299947.000000,5.000000,5.000000,18301.000000

- #### the result in correct and logic range

# categorical Sanity Check

In [13]:
cat_cols =df.select_dtypes(exclude='number').columns.to_list() 
cat_cols

['Brand', 'Model', 'Fuel', 'Transmission']

In [14]:
df[cat_cols].describe().T

             count unique       top  freq
Brand         8000     10      Audi   851
Model         8000     30    Accord   302
Fuel          8000      4  Electric  2074
Transmission  8000      3    Manual  2707

- ### show each uniqe values in each colunm sorted

In [15]:
def categories_check(cat_idx) : 
    values = np.sort(df[cat_cols[cat_idx]].unique()) 
    return cat_cols[cat_idx] , values

In [16]:
for it in range(len(cat_cols)) : 
    print(categories_check(it)) 
    print(10 * '*')

('Brand', array(['Audi', 'BMW', 'Chevrolet', 'Ford', 'Honda', 'Hyundai', 'Kia',
       'Mercedes', 'Toyota', 'Volkswagen'], dtype=object))
**********
('Model', array(['3 Series', '5 Series', 'A3', 'A4', 'Accord', 'C-Class', 'CR-V',
       'Camry', 'Civic', 'Corolla', 'E-Class', 'Elantra', 'Equinox',
       'Explorer', 'Fiesta', 'Focus', 'GLA', 'Golf', 'Impala', 'Malibu',
       'Optima', 'Passat', 'Q5', 'RAV4', 'Rio', 'Sonata', 'Sportage',
       'Tiguan', 'Tucson', 'X5'], dtype=object))
**********
('Fuel', array(['Diesel', 'Electric', 'Hybrid', 'Petrol'], dtype=object))
**********
('Transmission', array(['Automatic', 'Manual', 'Semi-Automatic'], dtype=object))
**********

#### check uniqe values of Brand

In [17]:
df['Brand'].unique()

<ArrowStringArray>
['Volkswagen',        'BMW',    'Hyundai',      'Honda',   'Mercedes',
       'Audi',       'Ford',        'Kia',  'Chevrolet',     'Toyota']
Length: 10, dtype: str

In [18]:
brand_to_models = df.groupby("Brand")["Model"].unique().apply(list).to_dict() 
brand_to_models

{'Audi': ['A3', 'A4', 'Q5'],
 'BMW': ['5 Series', 'X5', '3 Series'],
 'Chevrolet': ['Malibu', 'Impala', 'Equinox'],
 'Ford': ['Focus', 'Fiesta', 'Explorer'],
 'Honda': ['CR-V', 'Civic', 'Accord'],
 'Hyundai': ['Sonata', 'Elantra', 'Tucson'],
 'Kia': ['Sportage', 'Optima', 'Rio'],
 'Mercedes': ['E-Class', 'GLA', 'C-Class'],
 'Toyota': ['Camry', 'Corolla', 'RAV4'],
 'Volkswagen': ['Golf', 'Tiguan', 'Passat']}

In [19]:
df.iloc[0, :]

Brand               Volkswagen
Model                     Golf
Year                      2007
EngineSize                 3.2
Fuel                    Hybrid
Transmission    Semi-Automatic
Mileage                  33948
Doors                        5
OwnerCount                   4
Price                     9721
Name: 9254, dtype: object

# checkpoint

- #### we will make this step to save all progress and use it in next step of workflow

In [20]:
%store X_test 
%store y_test
%store df 
%store numrical_cols 
%store cat_cols

Stored 'X_test' (DataFrame)
Stored 'y_test' (Series)
Stored 'df' (DataFrame)
Stored 'numrical_cols' (list)
Stored 'cat_cols' (list)

#### to retrive it agin use ====> `%store -r files name`